// import '@/styles/globals.css'
import { AppConstants } from '@/constants';
import Layout from '@/containers/layout';
import GlobalStyles from '@/styles/global';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { Fragment } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import { wrapper } from '@/store';
import NextNProgress from 'nextjs-progressbar';
import { SessionProvider } from 'next-auth/react';
import { GetServerSidePropsContext } from 'next';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]';

const App = ({ Component, pageProps: { session, ...pageProps } }: AppProps) => {
  return (
    <SessionProvider session={session}>
      <Fragment>
        <Head>
          <title>{AppConstants.NAME}</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta charSet="utf-8" />
          <link rel="icon" href="/favicon.ico" />
          <style>
            @import url('https://fonts.googleapis.com/css2?family=Montserrat&display=swap');
          </style>
        </Head>
        <GlobalStyles />
        <NextNProgress />
        <Layout isAuth={pageProps?.isAuth}>
          <Component {...pageProps} />
        </Layout>
      </Fragment>
    </SessionProvider>
  );
}

export const getServerSideProps = async ({ req, res }: GetServerSidePropsContext) => {
  const session = await getServerSession(req, res, authOptions);
  return {
    props: {
      isAuth: (session && session?.jwt && session?.user),
    }
  }
}

export default wrapper.withRedux(App);